## 2.5.2.1.python_rss

In [1]:
# ElementTree 모듈 로드
from xml.etree import ElementTree

In [2]:
# parse() 함수로 파일을 읽고 ElementTree 객체를 생성
tree = ElementTree.parse('rss.xml')

In [3]:
# getroot() 메서드로 XML의 루트 element를 추출
root = tree.getroot()

In [4]:
import pandas as pd

In [5]:
df_list = []
for item in root.findall('channel/item/description/body/location/data'):
    # find() 메서드로 element 탐색, text 속성으로 값을 추출
    tm_ef = item.find('tmEf').text
    tmn = item.find('tmn').text
    tmx = item.find('tmx').text
    wf = item.find('wf').text
    df = pd.DataFrame({
        '일시': [tm_ef],
        '최저기온': [tmn],
        '최고기온': [tmx],
        '날씨': [wf]
    })
    df_list.append(df)
weather = pd.concat(df_list)
weather

                  일시 최저기온 최고기온     날씨
0   2020-06-25 00:00   21   26  흐리고 비
0   2020-06-25 12:00   21   26  흐리고 비
0   2020-06-26 00:00   21   29  흐리고 비
0   2020-06-26 12:00   21   29   구름많음
0   2020-06-27 00:00   22   29   구름많음
..               ...  ...  ...    ...
0   2020-06-29 00:00   23   26  흐리고 비
0   2020-06-29 12:00   23   26  흐리고 비
0   2020-06-30 00:00   22   26  흐리고 비
0   2020-07-01 00:00   22   26  흐리고 비
0   2020-07-02 00:00   22   27     흐림

[533 rows x 4 columns]

In [6]:
type(weather)

pandas.core.frame.DataFrame

In [7]:
weather.to_csv('weather.csv')

In [8]:
ex = pd.ExcelWriter('weather.xlsx')
weather.to_excel(ex, '.', index=False)
ex.save()

In [9]:
weather.reset_index(drop=True, inplace=True)

In [10]:
weather.to_json('weather.json')

In [11]:
import sqlite3
from pandas.io import sql
import os

In [12]:
with sqlite3.connect(os.path.join('.', 'sqliteDB')) as con:
    try:
        weather.to_sql(name='WEATHER_INFO', con=con, index=False, if_exists='append')
    except Exception as e:
        print(str(e))
        
    query = 'SELECT * FROM WEATHER_INFO'
    df1 = pd.read_sql(query, con=con)

In [13]:
df1

                    일시 최저기온 최고기온     날씨
0     2020-06-25 00:00   21   26  흐리고 비
1     2020-06-25 12:00   21   26  흐리고 비
2     2020-06-26 00:00   21   29  흐리고 비
3     2020-06-26 12:00   21   29   구름많음
4     2020-06-27 00:00   22   29   구름많음
...                ...  ...  ...    ...
1061  2020-06-29 00:00   23   26  흐리고 비
1062  2020-06-29 12:00   23   26  흐리고 비
1063  2020-06-30 00:00   22   26  흐리고 비
1064  2020-07-01 00:00   22   26  흐리고 비
1065  2020-07-02 00:00   22   27     흐림

[1066 rows x 4 columns]

In [14]:
ex1 = pd.ExcelWriter('weather2.xlsx')
df1.to_excel(ex1, '.', index=False)
ex1.save()

In [15]:
df2 = pd.read_excel('weather2.xlsx')

In [16]:
df2

                    일시  최저기온  최고기온     날씨
0     2020-06-25 00:00    21    26  흐리고 비
1     2020-06-25 12:00    21    26  흐리고 비
2     2020-06-26 00:00    21    29  흐리고 비
3     2020-06-26 12:00    21    29   구름많음
4     2020-06-27 00:00    22    29   구름많음
...                ...   ...   ...    ...
1061  2020-06-29 00:00    23    26  흐리고 비
1062  2020-06-29 12:00    23    26  흐리고 비
1063  2020-06-30 00:00    22    26  흐리고 비
1064  2020-07-01 00:00    22    26  흐리고 비
1065  2020-07-02 00:00    22    27     흐림

[1066 rows x 4 columns]